# Generated by Django 5.2.4 on 2025-08-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchannel',
            name='category',
            field=models.CharField(blank=True, null=True, verbose_name='Категория канала'),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='country',
            field=models.CharField(blank=True, null=True, verbose_name='Страна канала'),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='language',
            field=models.CharField(blank=True, null=True, verbose_name='Язык канала'),
        ),
    ]
