# Generated by Django 5.2.4 on 2025-09-12 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parser', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmoderator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderated_channels', to=settings.AUTH_USER_MODEL, verbose_name='Модератор'),
        ),
        migrations.AddField(
            model_name='channelstats',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.telegramchannel', verbose_name='Канал'),
        ),
        migrations.AddField(
            model_name='channelmoderator',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderators', to='parser.telegramchannel', verbose_name='Канал'),
        ),
        migrations.AlterUniqueTogether(
            name='channelmoderator',
            unique_together={('user', 'channel')},
        ),
    ]
