# Generated by Django 5.2.4 on 2025-09-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramchannel',
            name='category',
            field=models.CharField(blank=True, db_index=True, null=True, verbose_name='Категория канала'),
        ),
    ]
