# Generated by Django 5.2.4 on 2025-09-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=60, unique=True, verbose_name='URL-идентификатор')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('is_editorial', models.BooleanField(default=False, verbose_name='Редакторская подборка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок на главной')),
                ('image_url', models.CharField(blank=True, verbose_name='обложка группы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'db_table': 'groups',
            },
        ),
    ]
