# Generated by Django 5.2.4 on 2025-09-15 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_channels', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoGroupRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, verbose_name='Категория')),
                ('materialize', models.BooleanField(default=True, verbose_name='Материализовать в M2M')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_rule', to='group_channels.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Правило автоподборки',
                'verbose_name_plural': 'Правила автоподборок',
                'db_table': 'auto_group_rules',
            },
        ),
    ]
