# Generated by Django 5.2.4 on 2025-07-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_channels', '0005_group_channels_alter_group_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=60, unique=True, verbose_name='URL-идентификатор'),
        ),
    ]
