# Generated by Django 5.2.4 on 2025-08-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_channels', '0007_alter_group_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_editorial',
            field=models.BooleanField(default=False, verbose_name='Редакторская подборка'),
        ),
        migrations.AddField(
            model_name='group',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок на главной'),
        ),
    ]
